/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TablaRouteImport } from './routes/tabla'
import { Route as LlaveRouteImport } from './routes/llave'
import { Route as GoleadoresRouteImport } from './routes/goleadores'
import { Route as FixtureRouteImport } from './routes/fixture'
import { Route as EquiposRouteImport } from './routes/equipos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'

const TablaRoute = TablaRouteImport.update({
  id: '/tabla',
  path: '/tabla',
  getParentRoute: () => rootRouteImport,
} as any)
const LlaveRoute = LlaveRouteImport.update({
  id: '/llave',
  path: '/llave',
  getParentRoute: () => rootRouteImport,
} as any)
const GoleadoresRoute = GoleadoresRouteImport.update({
  id: '/goleadores',
  path: '/goleadores',
  getParentRoute: () => rootRouteImport,
} as any)
const FixtureRoute = FixtureRouteImport.update({
  id: '/fixture',
  path: '/fixture',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposRoute = EquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/equipos': typeof EquiposRoute
  '/fixture': typeof FixtureRoute
  '/goleadores': typeof GoleadoresRoute
  '/llave': typeof LlaveRoute
  '/tabla': typeof TablaRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/equipos': typeof EquiposRoute
  '/fixture': typeof FixtureRoute
  '/goleadores': typeof GoleadoresRoute
  '/llave': typeof LlaveRoute
  '/tabla': typeof TablaRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/equipos': typeof EquiposRoute
  '/fixture': typeof FixtureRoute
  '/goleadores': typeof GoleadoresRoute
  '/llave': typeof LlaveRoute
  '/tabla': typeof TablaRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/equipos'
    | '/fixture'
    | '/goleadores'
    | '/llave'
    | '/tabla'
    | '/api/public/bootstrap-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/equipos'
    | '/fixture'
    | '/goleadores'
    | '/llave'
    | '/tabla'
    | '/api/public/bootstrap-admin'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/equipos'
    | '/fixture'
    | '/goleadores'
    | '/llave'
    | '/tabla'
    | '/api/public/bootstrap-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EquiposRoute: typeof EquiposRoute
  FixtureRoute: typeof FixtureRoute
  GoleadoresRoute: typeof GoleadoresRoute
  LlaveRoute: typeof LlaveRoute
  TablaRoute: typeof TablaRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tabla': {
      id: '/tabla'
      path: '/tabla'
      fullPath: '/tabla'
      preLoaderRoute: typeof TablaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llave': {
      id: '/llave'
      path: '/llave'
      fullPath: '/llave'
      preLoaderRoute: typeof LlaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goleadores': {
      id: '/goleadores'
      path: '/goleadores'
      fullPath: '/goleadores'
      preLoaderRoute: typeof GoleadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixture': {
      id: '/fixture'
      path: '/fixture'
      fullPath: '/fixture'
      preLoaderRoute: typeof FixtureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos': {
      id: '/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof EquiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EquiposRoute: EquiposRoute,
  FixtureRoute: FixtureRoute,
  GoleadoresRoute: GoleadoresRoute,
  LlaveRoute: LlaveRoute,
  TablaRoute: TablaRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
